name: build-equifuzz-container
on: [push]
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: |
          podman build -t ghcr.io/mpardalos/equifuzz:v0.1.0.0 -t ghcr.io/mpardalos/equifuzz:latest -f Containerfile .

      - name: Push image to registry
        run: |
          podman push ghcr.io/mpardalos/equifuzz:latest

      - name: Save image to archive
        run: |
          podman save equifuzz | gzip > equifuzz.tar.gz

      - name: Upload container image as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: container-artifact
          path: equifuzz.tar.gz
